# Generated by Django 5.1.5 on 2025-04-18 05:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.CharField(choices=[('front', 'Frontstage'), ('back', 'Backstage')], default='front', help_text='Distinguish front‑end vs admin users', max_length=10, verbose_name='user type')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='帳號')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='信箱')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓')),
                ('address', models.TextField(blank=True, null=True, verbose_name='通訊地址')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否為員工或管理員')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='軟刪除')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='註冊時間')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='暱稱')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='手機')),
                ('mcoin', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('member_level', models.CharField(choices=[('一般', '一般'), ('VIP', 'VIP')], default='一般', max_length=10)),
                ('member_type', models.CharField(choices=[('會員', '會員'), ('創作者', '創作者')], default='會員', max_length=10)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='累計登入失敗次數')),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'back'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'back'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to=settings.AUTH_USER_MODEL, verbose_name='最後修改者')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255, verbose_name='分類')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'back'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_created', to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'back'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_updated', to=settings.AUTH_USER_MODEL, verbose_name='最後修改者')),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.PositiveIntegerField(help_text='角色層級，數字越小權限越高', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'back'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_created', to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
                ('permissions', models.ManyToManyField(related_name='roles', to='common_models.permission')),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'back'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_updated', to=settings.AUTH_USER_MODEL, verbose_name='最後修改者')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='common_models.role'),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=100)),
                ('condition', models.JSONField(help_text="權限規則的條件設定，例如 {'region': ['TW', 'JP']}")),
                ('priority', models.IntegerField(default=0, help_text='數字越大優先度越高')),
                ('is_active', models.BooleanField(default=True)),
                ('permissions', models.ManyToManyField(related_name='rules', to='common_models.permission')),
            ],
        ),
    ]
